Images:
  ApiServer: $(IMAGES_APISERVER)
  Artifact: $(IMAGES_ARTIFACT)
  OAuthProxy: $(IMAGES_OAUTHPROXY)
  PersistentAgent: $(IMAGES_PERSISTENTAGENT)
  ScheduledWorkflow: $(IMAGES_SCHEDULEDWORKFLOW)
  Cache: $(IMAGES_CACHE)
  MoveResultsImage: $(IMAGES_MOVERESULTSIMAGE)
  MariaDB: $(IMAGES_MARIADB)
  MlmdEnvoy: $(IMAGES_MLMDENVOY)
  MlmdGRPC: $(IMAGES_MLMDGRPC)
  MlmdWriter: $(IMAGES_MLMDWRITER)
  CRDViewer: $(IMAGES_CRDVIEWER)
  VisualizationServer: $(IMAGES_VISUALIZATIONSERVER)
DSPO:
  HealthCheck:
    Database:
      ConnectionTimeout: $(DSPO_HEALTHCHECK_DATABASE_CONNECTIONTIMEOUT)
    ObjectStore:
      ConnectionTimeout: $(DSPO_HEALTHCHECK_OBJECTSTORE_CONNECTIONTIMEOUT)
  RequeueTime: $(DSPO_REQUEUE_TIME)
