apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: kfp-tekton
  name: webhook-leaderelection-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leader-election-clusterrole
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: datasciencepipelinesapplications-controller
