apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: data-science-pipelines-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: kfp-tekton
  namespace: datasciencepipelinesapplications-controller
  name: webhook
