apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: kfp-tekton
    pipeline.tekton.dev/release: devel
    version: devel
  name: exithandlers.custom.tekton.dev
spec:
  group: custom.tekton.dev
  names:
    categories:
    - tekton
    - tekton-pipelines
    - openshift-pipelines
    kind: ExitHandler
    plural: exithandlers
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
