resources:
- clusterrole.clusteraccess.yaml
- clusterrolebinding.clusteraccess.yaml
- deployment.yaml
- mutatingwebhookconfig.yaml
- role.yaml
- rolebinding.yaml
- secret.yaml
- service.yaml
- serviceaccount.yaml
- validatingwebhookconfig.yaml