apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: data-science-pipelines-operator
    app.kubernetes.io/component: kfp-driver
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: kubeflow-pipeline
  name: kfp-driver-cluster-access-clusterrole
rules:
- apiGroups:
  - tekton.dev
  resources:
  - runs
  - customruns
  - runs/finalizers
  - customruns/finalizers
  - runs/status
  - customruns/status
  - pipelineruns
  - task
  - taskruns
  - conditions
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
