apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: ckfp-driver
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: driver
    app.kubernetes.io/part-of: kubeflow-pipeline
    app.kubernetes.io/version: devel
  name: driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kfp-driver
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: driver
      app.kubernetes.io/part-of: kubeflow-pipeline
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: kfp-driver
        app.kubernetes.io/component: kfp-driver
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: driver
        app.kubernetes.io/part-of: kubeflow-pipeline
        app.kubernetes.io/version: devel
    spec:
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LEADERELECTION_NAME
          value: config-leader-election
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: tekton.dev/pipeline
        image: quay.io/internaldatahub/tekton-driver:2.0.0
        imagePullPolicy: Always
        name: driver
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 65532
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: driver
