apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: data-science-pipelines-operator
    app.kubernetes.io/component: kfp-driver
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: kubeflow-pipeline
  namespace: datasciencepipelinesapplications-controller
  name: kfp-driver
