apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: data-science-pipelines-pipeline-loops
    app.kubernetes.io/name: data-science-pipelines-operator
  namespace: datasciencepipelinesapplications-controller
  name: data-science-pipelines-pipelineloop-webhook
