apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: data-science-pipelines-tekton
  name: kfptask-controller-cluster-access-clusterrole
rules:
- apiGroups:
  - tekton.dev
  resources:
  - runs
  - customruns
  - taskruns
  - pipelineruns
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - runs/status
  - customruns/status
  - taskruns/status
  - pipelineruns/status
  - runs/finalizers
  - customruns/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - custom.tekton.dev
  resources:
  - kfptasks
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
