allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: kubeflow-anyuid provides all features of the restricted
      SCC but allows users to run with any UID and any GID.
  name: anyuid-operator-tekton
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:kubeflow:metadatadb
- system:serviceaccount:kubeflow:minio
- system:serviceaccount:kubeflow:default
- system:serviceaccount:kubeflow:pipeline-runner
- system:serviceaccount:kubeflow:cache
- system:serviceaccount:kubeflow:cache-deployer-sa
- system:serviceaccount:kubeflow:metadata-grpc-server
- system:serviceaccount:kubeflow:metadata-writer
- system:serviceaccount:kubeflow:ml-pipeline
- system:serviceaccount:kubeflow:ml-pipeline-persistenceagent
- system:serviceaccount:kubeflow:ml-pipeline-scheduledworkflow
- system:serviceaccount:kubeflow:ml-pipeline-ui
- system:serviceaccount:kubeflow:ml-pipeline-viewer-crd-service-account
- system:serviceaccount:kubeflow:ml-pipeline-visualizationserver
- system:serviceaccount:kubeflow:mysql
- system:serviceaccount:kubeflow:data-science-pipelines-operator-csi-s3
- system:serviceaccount:kubeflow:data-science-pipelines-operator-csi-attacher
- system:serviceaccount:kubeflow:data-science-pipelines-operator-csi-provisioner
- system:serviceaccount:openshift-pipelines:data-science-pipelines-operator-driver
- system:serviceaccount:openshift-pipelines:data-science-pipelines-operator-exithandler-controller
- system:serviceaccount:openshift-pipelines:data-science-pipelines-operator-exithandler-webhook
- system:serviceaccount:openshift-pipelines:tektonpipelineloop-controller
- system:serviceaccount:openshift-pipelines:tektonpipelineloop-webhook
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
