apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.applications.yaml
- crd.clusterworkflowtemplates.yaml
- crd.cronworkflows.yaml
- crd.viewers.yaml
- crd.workflowartifactgctasks.yaml
- crd.workfloweventbinding.yaml
- crd.workflows.yaml
- crd.workflowtaskresult.yaml
- crd.workflowtaskset.yaml
- crd.workflowtemplate.yaml
