apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipeline-loops
  name: pipelineloop-controller-cluster-access-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelineloop-controller-cluster-access-clusterrole
subjects:
- kind: ServiceAccount
  name: pipelineloop-controller
  namespace: datasciencepipelinesapplications-controller
