apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipeline-loops
    app.kubernetes.io/name: data-science-pipelines-operator
  namespace: datasciencepipelinesapplications-controller
  name: pipelineloop-controller
