apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.workflow-controller-configmap.yaml
- deployment.workflow-controller.yaml
- priorityclass.yaml
- serviceaccount.argo.yaml
